@c SPDX-FileCopyrightText: 2023 Fredrik Salomonsson <plattfot@posteo.net>
@c
@c SPDX-License-Identifier: GPL-3.0-or-later

\input texinfo
@c -*-texinfo-*-

@c %**start of header
@setfilename pinentry-rofi.info
@documentencoding UTF-8
@settitle Pinentry-Rofi Reference Manual
@c %**end of header

@include version.texi

@copying
Copyright @copyright{} 2020 Fredrik Salomonsson

Permission is granted to copy, distribute and/or modify this document
under the terms of the GNU Free Documentation License, Version 1.3 or
any later version published by the Free Software Foundation; with no
Invariant Sections, no Front-Cover Texts, and no Back-Cover Texts.  A
copy of the license is included in the section entitled ``GNU Free
Documentation License''.
@end copying

@dircategory The Algorithmic Language Scheme
@direntry
* Pinentry-Rofi: (pinentry-rofi).
@end direntry

@titlepage
@title The Pinentry-Rofi Manual
@author Fredrik Salomonsson

@page
@vskip 0pt plus 1filll
Edition @value{EDITION} @*
@value{UPDATED} @*

@insertcopying
@end titlepage

@contents

@c *********************************************************************
@node Top
@top Pinentry-Rofi

This document describes Pinentry-Rofi version @value{VERSION}.

@menu
* Introduction::                Why Pinentry-Rofi?
@end menu

@c *********************************************************************
@node Introduction
@chapter Introduction

Based on
@url{https://gist.github.com/sardemff7/759cbf956bea20d382a6128c641d2746,this
gist}

Simple pinentry gui using @command{rofi} written in GNU guile.

It's similar in functionality as the gist but this one doesn't force
the width to be 27 and doesn't depend on systemd.

I also wanted a small project which I could use to practice writing
GNU guile.

@bye
